---
name: lint

on: # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            go.sum

      - name: Ensure all files were formatted as per gofmt
        run: |
          [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
