---
name: test

on: # yamllint disable-line rule:truthy
  push:
  pull_request:

permissions:
  deployments: write
  contents: write

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            go.sum

      - name: go test
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...

      - name: upload coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # use https://github.com/grafana/alloy/blob/main/.github/workflows/fuzz-go.yml
      - name: run fuzzing
        run: |
          go test -fuzz=. -fuzztime=30s

      - name: run benchmark
        run: |
          go test -bench=. -benchmem -run=^$ ./... | tee output.txt

      - name: store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: go benchmark
          tool: "go"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: "130%"
          comment-on-alert: true
          fail-on-alert: false
          fail-threshold: "200%"
          alert-comment-cc-users: "@ne-bknn"
          auto-push: true
