---
name: test

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            go.sum

      - name: go test
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...

      - name: upload coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
